default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
  node: 22.2.0
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        name: Run black on docs
        args:
          - --line-length=110
        alias: blacken-docs
        additional_dependencies: ['rich>=12.4.4', 'hatchling==1.26.3']
