build-backend = "setuptools.build_meta"

[project]
name = "my-package"
version = "0.1.0"
description = "A sample Python project"
dependencies = [
    "flask>=2.0.0"
]

[tool.poetry]
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.3.0"
]
