[build-system]
requires = [
    "setuptools>=57.0.0",
    "wheel>=0.36.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "my-package"
version = "0.1.0"
description = "A sample Python project"
dependencies = [
    "requests>=2.25.1",
    "flask>=2.0.0"
]

[tool.poetry]
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.3.0"
]
