name: build-docker-and-push

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build Docker image and push
        run: |
         docker buildx build -o - . > my-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          path: my-app.tar
          
      
  use-and-cache:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    needs: build-and-upload

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
       
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Load Docker image
      run: |
        docker import ./artifact/my-app.tar my-app:latest
        docker images

    - name: Push to local Docker registry
      run: |
        docker tag my-app:latest localhost:5000/my-app:latest
        docker push localhost:5000/my-app:latest      
        
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image using cache
      run: |
        docker buildx build -t localhost:5000/my-app:latest2 --cache-from=type=registry,ref=localhost:5000/my-app:latest .
        # docker push localhost:5000/my-app:latest
        docker images
 #       docker build --cache-from=localhost:5000/my-app:latest -t my-app:cached .
    
  pull-again:
   runs-on: ubuntu-latest
   needs: use-and-cache
   steps:
    - name: Re pull image
      run: |
        docker images
