name: build-docker-cache

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load Docker cache
        run: |
          mkdir -p /tmp/docker-cache
          
      # - name: "restore"
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: docker-cache-local-main
      #     path: ${{github.workspace}}/docker-cache
      #     run-id: 12284732784
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: my-app:latest
          cache-from: type=local,src=${{github.workspace}}/docker-cache
          cache-to: type=local,dest=${{github.workspace}}/docker-cache
          
      - name: "stash"
        uses: apache/infrastructure-actions/stash/save@main
        with:
          key: 'docker-cache-local'
          path: ${{github.workspace}}/docker-cache
          
      
  download-and-rebuild:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      - name: "restore"
        uses: apache/infrastructure-actions/stash/restore@main
        with:
          key: docker-cache-local
          path: ${{github.workspace}}/docker-cache2
  #     # Download the Docker image artifact
  #     - name: Download Docker image artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docker-image

  #     # Load the Docker image
  #     - name: Load Docker image
  #       run: |
  #         docker load -i my-app.tar

      # Download the cach
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: my-app:latest
          cache-from: type=local,src=${{github.workspace}}/docker-cache2
          cache-to: type=local,dest=${{github.workspace}}/docker-cache
