name: Monitor build-system.requires in pyproject.toml

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as necessary (5 min minimum)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install toml requests
