name: Monitor build-system.requires in pyproject.toml

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as necessary (5 min minimum)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Default APT Retries
        run: |
          # Check the default retries value for apt
          default_retries=$(apt-config dump | grep -i "Acquire::Retries" | awk '{print $2}')
          
          # Display the default retries value or a message if not set
          if [ -z "$default_retries" ]; then
            echo "Acquire::Retries is not set. The default is likely 0 (no retries)."
          else
            echo "Default retries for apt-get: $default_retries"
          fi
      - name: Display Full APT Configuration
        run: |
          echo "Dumping full APT configuration:"
          apt-config dump
